config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Defines the root path route ("/")
  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update", as: :update_blog_post
  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  #  we can ignore typing all the above request and can simply use one line code for all actions

  resources :blog_posts
  root "blog_posts#home"
  get "about", to: "blog_posts#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable,  :recoverable, :rememberable, :validatable
  # :registerable,
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
#   before_action :authenticate_user!, only: [:create, :edit, :destroy, :update]

    # before_action :set_blog_post, expect: [:index, :new, :create]
        # #           we can also write as only: [:show, :edit, :destroy, :update]
    def index
        @blog_posts = BlogPost.all
    end

    def show
            @blog_post = BlogPost.find(params[:id])
        rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def new
            @blog_post = BlogPost.new
    end

    def create
            @blog_post = BlogPost.new(blog_post_params)
            if @blog_post.save
                redirect_to @blog_post
            else
              render :new, status: :unprocessable_entity
            end
    end

    def edit
            @blog_post = BlogPost.find(params[:id])
    end

    def update
            @blog_post = BlogPost.find(params[:id])
            if @blog_post.update(blog_post_params)
                redirect_to @blog_post
            else
              render :edit, status: :unprocessable_entity
            end
    end

     def destroy
                @blog_post = BlogPost.find(params[:id])
                @blog_post.destroy
                redirect_to blog_posts_path
    end

    private

    def blog_post_params
            params.require(:blog_post).permit(:title, :body)
    end

    # def set_blog_post
        # @blog_post = BlogPost.find_by(params[:id])
    #     # rescue ActiveRecord::RecordNotFound
    #     #         redirect_to root_path

    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
<% form.object.errors.any? %>
    <div>
        <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
        <%end%>
    </div>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title  %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_area :body  %>
    </div>
    <%= form.button %>
<% end %>

app/views/blog_posts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Blog Articles", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", blog_posts_path, class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/blog_posts/about.html.erb
<h1>This is a simple blog application that uses CRUD operations</h1>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>
<div class= "container-fluid">
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
<br>
  <li class="nav-item">
    <%= link_to 'Back', blog_post_path(@blog_post),class: "btn btn-secondary"%>
    </li><br>
  <li class="nav-item">
    <%= link_to 'Delete this article', blog_post_path(@blog_post), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </li></ul>
</div>

app/views/blog_posts/home.html.erb
<h1>Welcome to Blog application</h1>

app/views/blog_posts/index.html.erb
<h1 class= "text-blue-900 animate-pulse m-1.5">My blog</h1>

<% @blog_posts.each do |blog_post| %>
<div  class: "text-blue-500 hover:underline">
<h2 class="text-xl font-semibold"><%= link_to blog_post.title, blog_post%></h2>
<%= blog_post.body %>
</div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New blog</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title %></h1>
<%= @blog_post.body %>
<div class="container-fluid">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <br>
    <li class="nav-item"><%= link_to "Edit blog post", edit_blog_post_path(@blog_post),class: "btn btn-primary" %></li><br>
    <li class="nav-item"><%= link_to "back", blog_posts_path, class: "btn btn-secondary" %></li>
    <ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Articles CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'blog_posts/header' %>
    <div class ="container">
      <br>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <br>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
  </body>
</html>